=== CorTal/TRV/regle.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT regle (terrains, contraintes, unites)>
<!ELEMENT terrains (terrain_defaut, (terrain+))>
<!ELEMENT terrain_defaut EMPTY>
<!ATTLIST terrain_defaut type CDATA #REQUIRED>
<!ATTLIST terrain_defaut contrainte_defaut CDATA #REQUIRED>
<!ELEMENT terrain EMPTY>
<!ATTLIST terrain type CDATA #REQUIRED>
<!ATTLIST terrain contrainte_defaut CDATA #REQUIRED>
<!ATTLIST terrain obstacle CDATA #IMPLIED>
<!ELEMENT contraintes (contrainte)+>
<!ELEMENT contrainte EMPTY>
<!ATTLIST contrainte type CDATA #REQUIRED>
<!ELEMENT unites (unite)+>
<!ELEMENT unite EMPTY>
<!ATTLIST unite type CDATA #REQUIRED>
<!ATTLIST unite deplacement CDATA #IMPLIED>
<!ATTLIST unite contrainte CDATA #IMPLIED>

=== CorTal/TRV/regle.xml
<!DOCTYPE regle SYSTEM "regle.dtd">

<regle>
	<contraintes>
		<contrainte type="avoine"/>
		<contrainte type="ble"/>
	</contraintes>
	<terrains>
		<terrain_defaut type="terrain" contrainte_defaut="avoine:2;ble:3"/>
		<terrain type="Marais" contrainte_defaut="avoine:1;ble:1"/>
		<terrain type="Foret" contrainte_defaut="avoine:5;ble:10"/>
		<terrain type="Montagne" contrainte_defaut="avoine:0;ble:0" obstacle="1"/>
		<terrain type="Colline" contrainte_defaut="avoine:2;ble:3"/>
		<terrain type="Riviere" contrainte_defaut="avoine:0;ble:0" obstacle="1"/>
	</terrains>
	<unites>
		<unite type="Cavalier" deplacement="terrain:2;Marais:3;Foret:5;Colline:2;Montagne:99;Riviere:99" contrainte="avoine:3;ble:2"/>
		<unite type="Infanterie" deplacement="terrain:1;Marais:5;Foret:3;Colline:3;Montagne:99;Riviere:99" contrainte="avoine:0;ble:2"/>
		<unite type="Artillerie" deplacement="terrain:5;Marais:10;Foret:10;Colline:10;Montagne:99;Riviere:99" contrainte="avoine:3;ble:5"/>
	</unites>
</regle>
